[global]
   workgroup = WORKGROUP
   server string = Skole Filserver
   security = user
   map to guest = bad user
   dns proxy = no

[Felles]
   path = /skole-data/felles
   browsable = yes
   writable = yes
   read only = no
   valid users = @elever @lærer

[Lærer_Privat]
   path = /skole-data/lærer
   browsable = yes
   writable = yes
   read only = no
   valid users = @lærer