[servers]
infra ansible_host=10.10.10.10 ansible_user=infra ansible_ssh_pass=passord/ssh
file ansible_host=10.10.10.20 ansible_user=fildeling ansible_ssh_pass=passord/ssh

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become_pass=sudopassord